### PR TITLE
fix libcli version definitions

### PR DESCRIPTION
**Pull request by belge-sel**
fixed minor typos and bumped old revision number

### CODE REVIEW

**Comment by dparrish** [comment]
That's a typo that's been around for a very long time, how did I not notice that before?

There's no functionality change though so I wouldn't make a new release. Can you drop the minor version back down to 6 please?

**Comment by belge-sel** [comment]
Minor version number is already 7 at this point. Check out the Makefile and releases for reference.

**Comment by belge-sel** [comment]
Any updates on this?

**Comment by JereLeppanen** [comment]
This would be nice. But I would suggest adding the following, for compatibility:
```
#define LIBCLI_VERISON_MINOR LIBCLI_VERSION_MINOR
#define LIBCLI_VERISON_REVISION LIBCLI_VERSION_REVISION
```

**Comment by RobSanders** [comment]
Concur on Jere's suggestion, if only to ensure anyone using the existing code will continue to work.  Will merge to the staging-1.10.8 branch (with Jere's suggestions), with slight change:
#define LIBCLI_VERSION_MINOR 10
#define LIBCLI_VERSION_RELEASE 7

#for compatability
#define LIBCLI_VERISON_MINOR LIBCLI_VERSION_MINOR
#define LIBCLI_VERISON_REVISION LIBCLI_VERSION_REVISION

**Comment by belge-sel** [comment]
@RobSanders please do not forget to bump version up if it is going to be "1.10.8"

**Comment by RobSanders** [comment]
Yep, going to do that as I start making direct changes to the branch.  I've been working on a change to the OPTIONAL_FLAG so it directly supports validators/completors.  We have a syntax change we'd like to support where it would look like:
   command [alpha | bravo ] cmdarg1 value1 cmdarg2 value2
and we'd register the OPTIONAL_FLAG to accept either alpha, bravo, or none of the above.  Right now the only acceptable value for an OPTIONAL_FLAG is the name of the flag ('verbose' for example).  Have the basic change done, still testing.

**Pull request merged**
